# Generated by Django 5.0.3 on 2024-03-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brewiten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brew_name', models.CharField(max_length=255)),
                ('Price', models.FloatField()),
                ('type_brews', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
            ],
        ),
    ]
